name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 1.1.0
author: Rody Davis <rody.davis.jr@gmail.com>
maintainer: Rody Davis (@AppleEducate)
homepage: https://github.com/fluttercommunity/app_review

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  package_info: ^0.4.0+13
  url_launcher: ^5.4.1
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.appleeducate.appreview
    pluginClass: AppReviewPlugin
