name: app_review_plus
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter. Fork by Innim. 
version: 2.1.3+1
repository: https://github.com/Innim/flutter_app_review
issue_tracker: https://github.com/Innim/flutter_app_review/issues

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  http: ^0.13.5
  package_info_plus: ^3.1.2
  url_launcher: ^6.1.6
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
