name: app_review_plus
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter. Fork by Innim. 
version: 2.1.3
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/fluttercommunity/app_review

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  http: ^0.13.5
  package_info_plus: ^3.1.2
  url_launcher: ^6.1.6
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreviewplus
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
