name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 2.1.1+1
author: Rody Davis <rody.davis.jr@gmail.com>
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/fluttercommunity/app_review

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'
  flutter: ^1.10.0

dependencies:
  http: ^0.13.0-nullsafety.0
  package_info_plus: ^1.0.0
  url_launcher: ^6.0.0-nullsafety.6
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
