name: app_review_plus
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter. Fork by Innim. 
version: 2.1.4
repository: https://github.com/Innim/flutter_app_review
issue_tracker: https://github.com/Innim/flutter_app_review/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  http: ^1.1.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.3
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
